// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcs525M4vTuAOgcHfHvHUJITOxkUzx8ms',
    appId: '1:250843394521:web:b42b2e8c8e53204089e9c8',
    messagingSenderId: '250843394521',
    projectId: 'gemicatestest',
    authDomain: 'gemicatestest.firebaseapp.com',
    storageBucket: 'gemicatestest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAkuJIX-BnVdfdx8uOwIGF1vmLIQg90Xc',
    appId: '1:250843394521:android:b948726169cf1e0489e9c8',
    messagingSenderId: '250843394521',
    projectId: 'gemicatestest',
    storageBucket: 'gemicatestest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARhxbDmtdilHJulyv12SP6n8P0Jo38rZM',
    appId: '1:250843394521:ios:84bd4de48ad0518b89e9c8',
    messagingSenderId: '250843394521',
    projectId: 'gemicatestest',
    storageBucket: 'gemicatestest.appspot.com',
    iosBundleId: 'com.example.gemicates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARhxbDmtdilHJulyv12SP6n8P0Jo38rZM',
    appId: '1:250843394521:ios:84bd4de48ad0518b89e9c8',
    messagingSenderId: '250843394521',
    projectId: 'gemicatestest',
    storageBucket: 'gemicatestest.appspot.com',
    iosBundleId: 'com.example.gemicates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcs525M4vTuAOgcHfHvHUJITOxkUzx8ms',
    appId: '1:250843394521:web:8dbe133055a4d9ea89e9c8',
    messagingSenderId: '250843394521',
    projectId: 'gemicatestest',
    authDomain: 'gemicatestest.firebaseapp.com',
    storageBucket: 'gemicatestest.appspot.com',
  );
}
